### ISSUE TITLE
Investigate URS000036A08E

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#20]
It looks a bit weird to me.

**Comment by rtobes** [comment]
Why?

**Comment by eparejatobes** [comment]
I'm not sure if it's what it claims to be

**Comment by rtobes** [comment]
These are the BLASTN results against bacteria at NCBI:

<img width="762" alt="screen shot 2016-04-24 at 22 07 05" src="https://cloud.githubusercontent.com/assets/833404/14770081/fbb761d6-0a68-11e6-865d-3f7d4327d5ab.png">

**Comment by eparejatobes** [comment]
Thank you, closing
