### ISSUE TITLE
General filtering routine

### ISSUE THREAD

**Issue by laughedelic** [era7bio/db.rna16S#28]
1. #26: for each seq drop assignments that are covered by a bigger seq
2. apply existing filters
3. #27: run MG7 on the DB and filter bad assignments
4. drop the seq-s for which LCA of their assignments yields something uninformative (i.e. doesn't pass filters from 2.)

@eparejatobes please, check this.

**Comment by eparejatobes** [comment]
Fine, as I told you. :+1: LGTC

**Comment by eparejatobes** [comment]
We need _all_ discarded sequences as part of the output, including the relevant information (tax assignment, whatever)

**Comment by laughedelic** [comment]
Done :shipit:
