### ISSUE TITLE
First release with the ohnosequences namespace

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#42]
After (at least) 
- [x] #32 
- [x] #36  
- [x] #38 
- [x] #43 
- [x] #44
- [x] #45 

Note that this should include generating all data; see #46

**Comment by laughedelic** [comment]
@eparejatobes is everything ready here?

**Comment by eparejatobes** [comment]
Is rnacentral updated?

**Comment by laughedelic** [comment]
Yes: [v0.7.0](https://github.com/ohnosequences/db.rnacentral/releases/tag/v0.7.0)

**Comment by eparejatobes** [comment]
If that has everything needed, then yes, we should release this after depending on a reasonable mg7 version for tests.

**Comment by laughedelic** [comment]
I'm a bit confused about you question and "If that has everything needed".. All issues that were planned there [are closed/merged](https://github.com/ohnosequences/db.rnacentral/issues?utf8=%E2%9C%93&q=updated%3A%3E2016-08-04%20) (except the update to RNAcentral v6). Is it what you mean?
Here's also open #46, but I wrote there that we don't have an immediate solution.

Regarding MG7, I'm working on it now. I'm going to 
- release 1.0.0-M5 after all refactoring
- then release this db with MG7 1.0.0-M5
- then run MG7 tests with this db
- then release MG7 1.0.0-RC1

**Comment by eparejatobes** [comment]
OK. About rnacentral, just this: https://github.com/ohnosequences/db.rnacentral/compare/v0.7.0...master if there's nothing important there, then let's keep going.

**Comment by laughedelic** [comment]
It's only org/docs/build updates 👌

**Comment by laughedelic** [comment]
@eparejatobes I'm thinking of using MG7 1.0-M4 (previous release) to generate the new release of this DB, because M5 is only about refactoring, so it won't make results here any better, but something may got broken. So I want to do it like this:
- release db.rna16s 0.10.0 using MG7 M4
- release MG7 M5
- use MG7 M5 and db-rna16s 0.10.0 to run MG7 test pipelines

(then release RC1 if everything is fine)

**Comment by eparejatobes** [comment]
OK from me.

**Comment by laughedelic** [comment]
I released v0.10.0 and launched `pick16SCandidates` overnight, but it has failed with "GC overhead limit exceeded". It's quite strange, because I used `r3.2xlarge` instance with 40GB of heap.

**Comment by laughedelic** [comment]
In general it feels very strange to make a release for data that yet has to be generated (and still may not)...

**Comment by laughedelic** [comment]
Finally it worked with 80GB of RAM. I'm running MG7 now.

**Comment by laughedelic** [comment]
Finally finished with this! [v0.10.0](https://github.com/ohnosequences/db.rna16s/releases/tag/v0.10.0) is released, generated data is where it's supposed to be:

```
s3://resources.ohnosequences.com/ohnosequences/db-rna16s/0.10.0/release/
```

@eparejatobes please, review it. I'm going to update MG7 to this version meanwhile.

**Comment by eparejatobes** [comment]
I'm working on it.

**Comment by eparejatobes** [comment]
See #48

**Comment by eparejatobes** [comment]
Closing this, already reviewed the data in #48
