### ISSUE TITLE
Update to RNACentral 6

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#59]
Once it is released.

**Comment by eparejatobes** [comment]
Removing from 1.0.0, as RNACentral 6.0 is still not released.

**Comment by eparejatobes** [comment]
There's now RNACentral 6.0, back to 1.0.0

**Comment by laughedelic** [comment]
Done in https://github.com/ohnosequences/db.rna16s/pull/65/commits/07baf09d1fac1e55b0051b577b10e6350a78cb1b
