### ISSUE TITLE
Remove SILVA data

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#61]
Almost all of it is part of ENA, and it's easier to maintain only one version of the database. We need to

- [x] parse the source column from RNACentral data
- [x] exclude sequences which come *only* from SILVA

**Comment by laughedelic** [comment]
Oops. Pushed to master accidentally. See 0f709f2d803fecac23a533da8b6d851f677e7a60. Will close it once the data is filtered.

**Comment by laughedelic** [comment]
Results are in 

```
s3://resources.ohnosequences.com/ohnosequences/db-rna16s/0.12.0-4-g0f709f2/pick16SCandidates/
```

This procedure dropped 16 050 _sequences_ (not assignments), those that come _only_ from SILVA. I also filtered out all assignments from SILVA, but I didn't count them (it's not so trivial). Number of sequences on this step:
- 364997 before (v0.12.0)
- 348947 after
