### ISSUE TITLE
Integrate assignments into the BLAST DB

### ISSUE THREAD

**Issue by laughedelic** [era7bio/db.rna16S#64]
I have an idea to add assignments list to the FASTA headers to integrate this information in the BLAST DB. This way one can get all the information (of what db.rna16s provides) from the BLAST results (by parsing the `stitle` output field).

We can keep the assignments table separately for any other use. Same about the FASTA for all the sequences in the DB, we can provide it with or without this additional information in the header.

The main point is that it would significantly simplify the assignment process in MG7:
- now we get assignments tables, load them all in memory and lookup each BLAST hit subject sequence to get its assignments from this in-memory map
- if we had this information in the BLAST DB, we would get this immediately in the BLAST hits output, so no need to load any additional tables in memory — less memory usage and less additional steps in the process

--- 

At first, I wanted to use `taxid_map` parameter of the `makeblastdb` command (see Table C8 in the [CLI Reference](https://www.ncbi.nlm.nih.gov/books/NBK279675/)), but I couldn't find any way to pass there several tax IDs. If anybody knows of any way to do it, it would be better, of course, then putting it in the headers.

---

@eparejatobes @rtobes what do you think about it?

**Comment by eparejatobes** [comment]
@laughedelic I think we already discussed this, and why it's neither possible nor a good idea. Closing?

**Comment by laughedelic** [comment]
Can you write here a short resume of the reason? So that we won't be coming back to this again.

**Comment by eparejatobes** [comment]
It's not a good idea because assignments are a function `sequence -> taxon`, not part of `sequence`s. It is not possible because BLAST expects a single taxonomy assignment for each sequence.

**Comment by rtobes** [comment]
As far as I know BLAST and NCBI in general expect a single taxonomy assignment for each sequence

**Comment by laughedelic** [comment]
I know, but my suggestion was a bit different:

> add assignments list to the FASTA headers to integrate this information in the BLAST DB. This way one can get all the information (of what db.rna16s provides) from the BLAST results (by parsing the `stitle` output field).

**Comment by eparejatobes** [comment]
Closing then.
