### ISSUE TITLE
Generate some stats after all filtering steps

### ISSUE THREAD

**Issue by laughedelic** [era7bio/db.rna16S#66]
- `summary.csv` table for each filter step gives us 
  + number of sequences (before/after)
  + number of assignments (accepted/rejected)
- `clusters.csv`: first filter clusters after the last step
  + clusters number
  + distribution of cluster sizes 

@eparejatobes what else?

**Comment by eparejatobes** [comment]
The LCA of each cluster?

**Comment by eparejatobes** [comment]
Closing as clustering, assignments etc no longer belongs here.
