### ISSUE TITLE
Make the last filter idempotent

### ISSUE THREAD

**Issue by laughedelic** [era7bio/db.rna16S#67]
Currently the **drop inconsistent assignments** step is not idempotent (repeating it may reject more assignments). How to fix it: 

- take the ancestors (e.g. grandparents) of the cluster members
- filter them using the same algorithm comparing (their) counts with the total
- keep those cluster members whose grandparents got accepted

This should be even a bit simpler than it is now.

**Comment by eparejatobes** [comment]
Closing. Any further development will be based in the version without assignments etc
