### ISSUE TITLE
Prepare 23S sequences reference DB

### ISSUE THREAD

**Issue by laughedelic** [era7bio/db.rna16S#68]
From https://github.com/ohnosequences/db.rna16s-paper-2017/issues/6#issuecomment-276719633:

> build a 23S reference sequence database (taxonomy assignments are irrelevant here); we only need to do this once, no need to update it afterwards.

> We can take sequences from our current release with "23S" in their header; that's enough.

**Comment by eparejatobes** [comment]
Closing. Any further development will be based in the version without assignments etc
