### ISSUE TITLE
new taxa IDs to filter for descendants

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#7]
I'll be adding here taxa that I think should be filtered out (all their descendants) from the db; Please @rtobes check those with which you are OK
- [x] [unclassified bacteria](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=2323&lvl=3&keep=1&srchmode=1&unlock)
- [x] [unclassified bacteria (miscellaneous)](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=49928&lvl=3&keep=1&srchmode=1&unlock)

**Comment by rtobes** [comment]
OK
