### ISSUE TITLE
Zero compile dependencies

### ISSUE THREAD

**Issue by laughedelic** [era7bio/db.rna16S#71]
I suggest to remove any compile-scoped dependencies, i.e. 
* use `sbt-buildinfo` (or manually sbt `sourceGenerators`) to get version/artifact name from the build (currently we use statika metadata generator, but we don't need it in compile scope)
* store data locations as `URI`s (currently we use aws-scala-tools for that)

The reason is very simple: this will let use avoid any dependency conflicts in cases when we want to use non-matching versions of MG7 and this DB. This is not just about regular dependencies updates, but about the ability to use the same DB (basically just the data references) in any project without any concerns about dependencies.

/cc @eparejatobes

**Comment by ncordon** [comment]
This does not apply anymore
