### ISSUE TITLE
Update to RNACentral v8

### ISSUE THREAD

**Issue by agarciamontoro** [era7bio/db.rna16S#80]
RNACentral release 8 was [published on December, 2017](http://blog.rnacentral.org/2017/12/rnacentral-release-8.html).

A quick test showed that version 2.0 ---and probably 1.x, although that was not specifically tested--- of `db.rna16s` (#76)  seems to be incompatible with this release, as the output FASTA file is completely empty. We need to study this update carefully .

Related: https://github.com/ohnosequences/db.rnacentral/issues/33

**Comment by eparejatobes** [comment]
Needs ohnosequences/api.rnacentral#8

**Comment by ncordon** [comment]
Probably done(?) since bump to v9 has already been done in #91
