### ISSUE TITLE
Actually release data for 1.1.0

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#82]
1.1.0 was released without modifying the code in 1.1.0-RC1: https://github.com/ohnosequences/db.rna16s/compare/v1.1.0-RC1...v1.1.0, but we didn't run any data generation. We need to copy 1.1.0-RC1 files to the relevant locations (and/or run any data generation, as needed).

**Comment by agarciamontoro** [comment]
Should I wait for this to be resolved before releasing 2.0.0 from master?

**Comment by eparejatobes** [comment]
> Should I wait for this to be resolved before releasing 2.0.0 from master?

No, we can release 2.0 now.

**Comment by laughedelic** [comment]
I've copied the data from 1.1.0-RC1 to `s3://resources.ohnosequences.com/ohnosequences/db-rna16s/1.1.0/`
