### ISSUE TITLE
[MOVE TO db.rna16s.assignments] Assign a set of taxonomy nodes to each reference (and precompute their LCA)

### ISSUE THREAD

**Issue by agarciamontoro** [era7bio/db.rna16S#85]
Each reference in the DB needs to be assigned to a set of nodes in the taxonomy tree from [ohnosequences/ncbitaxonomy](https://github.com/ohnosequences/ncbitaxonomy) repo. We may also compute the LCA of this set.

We need to:
- [ ] Document how to assign a sequence in the DB to a node in the taxonomy. Where is this information stored? How do we parse it?
- [ ] Document what to do in the cases a reference is assigned to each of the subtrees specified in ohnosequences/ncbitaxonomy#7.
- [ ] Code a function `Reference -> Seq[TaxonomyNode]` that implements the assignment.
- [ ] Decide how to store this information in this DB.
- [ ] Evaluate the function over all references and store the results with the precomputed LCA in the DB.

@eparejatobes, can you take charge of the documentation tasks?

Needs ohnosequences/ncbitaxonomy#7.

**Comment by eparejatobes** [comment]
Sure I can do this. This should be moved to a different repo/project though, otherwise we are forced to update the db itself everytime we change/correct assignments.

**Comment by eparejatobes** [comment]
that was the point of #72 (no description there, my fault)

**Comment by agarciamontoro** [comment]
> This should be moved to a different repo/project

Are you ok if I move this to [assignments.rna16s](https://github.com/ohnosequences/assignments.rna16s)?

> that was the point of #72 (no description there, my fault)

72 [was closed in #76](https://github.com/ohnosequences/db.rna16s/pull/76#issuecomment-364878744) by error, then? Or did I miss something there that solved this?

**Comment by eparejatobes** [comment]
#72 is solved inasmuch as assignments are no longer here; we still need to put them elsewhere.

> Are you ok if I move this to assignments.rna16s?

as these assignments will be checked/fixed (clustering, taxonomy tree coherence) I'd rather have a separate repo for them.

**Comment by agarciamontoro** [comment]
> I'd rather have a separate repo for them.

Sure! I'll create a repo later called `db.rna16s.assignments` (someday we should review all names and find a consistent way of generating them :p) and move this issue there.

I'll close this when that repo is ready.

**Comment by eparejatobes** [comment]
> someday we should review all names and find a consistent way of generating them

They basically correspond to packages

**Comment by agarciamontoro** [comment]
Closed in favour of https://github.com/ohnosequences/db.rna16s.assignments/issues/2.
