### ISSUE TITLE
Compute which sequences are amplified by which primers

### ISSUE THREAD

**Issue by agarciamontoro** [era7bio/db.rna16S#86]
For each sequence in the DB, we need to know which of the primers can be used to amplify it, so we can optimize the assignment in the near future,

I understand that we only need to align each pair of primers with each sequence and store the exact matches. Is this correct?

**Comment by rtobes** [comment]
Yes. 
One question to consider is the **orientation** of the reference sequences in the database. If all of them are oriented in the same orientation and that orientation is the same that the _E. coli_ reference sequence you would find always the F primer before the R primer. If you do not find the F primer it has not sense to continue searching for the R primer.

If the orientation is not the same for all the sequences in the reference database (which is highly probable) you will have to search for the primers F and R in the orientation that they are (https://github.com/ohnosequences/primers.16s/blob/master/v4v6/idt-checked-primers.md) and also the Reverse complementary F and R primers (CI-F and CI-R). In this last case the order to find them would be CI-R first and then CI-F.

**Comment by eparejatobes** [comment]
This should be in ohnosequences/primers.16s.

**Comment by agarciamontoro** [comment]
Is it there already? https://github.com/ohnosequences/primers.16s/issues/7 If so, then we can close this one.

**Comment by eparejatobes** [comment]
Yes!
