### ISSUE TITLE
Amplicon regions

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#88]
Given a set of left-right primers and read lengths we can extract the corresponding amplicon regions, compute which sequences collapse into one amplicon region, etc. Questions

1. Should all this be part of db.rna16s?
2. If so, how?

**Comment by eparejatobes** [comment]
We also need to specify how regions are going to be stored, the entries from which they come, etc.

**Comment by ncordon** [comment]
I think all the structure of https://github.com/ohnosequences/db.fragments16s covers this
