### ISSUE TITLE
Improve versioning scheme

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#93]
We have

1. the version of this code/artifact: what you need to add to your sbt build def
2. the versions of the 16S database, which should be part of the code as `sealed abstract class Version` etc. This should correspond to the predicate we use for selecting 16S sequences
3. The version of RNACentral data that is used as input

I think in 2. `Version` could have a `Set[RNACentral.Version]` of compatible input data.

**Comment by ncordon** [comment]
Done in #94
