### ISSUE TITLE
Replace fastarious with faster

### ISSUE THREAD

**Issue by agarciamontoro** [era7bio/db.rna16S#95]
We should use [faster](https://github.com/ohnosequences/faster) instead of [fastarious](https://github.com/ohnosequences/fastarious). The refactor should not be too difficult.

**Comment by ncordon** [comment]
I'm moving this to `db.rnacentral`

**Comment by agarciamontoro** [comment]
Oopsie, yes, we talked about it but completely forgot to do it, thanks!
